### ISSUE TITLE
Add mobile datatype option

### ISSUE THREAD

**Issue by ijaureguialzo** [FlorianRauscha/fastlane-plugin-demo_mode#4]
Hello @FlorianRauscha,

I'm trying to set mobile connection datatype, but the parameter is hardcoded to hidden, could you make it available as an option?

Thank you in advance.

**Comment by FlorianRauscha** [comment]
Thank you. I added the option "mobile_datatype" so you can set a mobile datatype. Possible parameters are listed in the README
